name: Flutter Test
on: workflow_dispatch
jobs:
  build:
    name: Testing Flutter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
    - name: Installing Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.3'
        channel: 'stable'
    - name: Running Flutter
      run: flutter create uk_flu 
    - name: Building App
      continue-on-error: true
      run: |
         cd uk_flu 
         flutter pub get 
         flutter build apk 
         flutter build appbundle
    - name: Uploading Folder and Files
      uses: actions/upload-artifact@v2
      with:
        name: All
        path: |
            uk_flu/build/app/outputs/flutter-apk
            uk_flu/build/app/outputs/bundle/release
      
    
